### ISSUE TITLE
no-arch packages are breaking downstream

### ISSUE THREAD

**Issue by jreback** [conda-forge/pytables-feedstock#19] opened 2017-10-03 10:27 UTC
looks like #18 is now creating no-arch packages, which I don't think works. recipe needs to revert 'numpy x.x'

xref https://github.com/pandas-dev/pandas/issues/17757

```
                            3.4.2               np112py27_1  conda-forge     
                             3.4.2               np112py35_1  conda-forge     
                             3.4.2               np112py36_1  conda-forge     
                             3.4.2               np113py27_1  conda-forge     
                             3.4.2               np113py35_1  conda-forge     
                             3.4.2               np113py36_1  conda-forge     
                             3.4.2                    py27_2  conda-forge     
                             3.4.2                    py35_2  conda-forge     
                             3.4.2                    py36_2  conda-forge     
```

**Comment by ocefpaf** [comment] 2017-10-03 13:45
That is not `noarch`, it is the same strategy used for wheels where we build with an old "enough" `numpy` and then run with the latest version that is backwards compatible.

I'll check the errors and see if this is the cause but I suspect it may be something else.

**Comment by isuruf** [comment] 2017-10-03 14:58
This might be the error, https://github.com/conda-forge/pytables-feedstock/commit/aac7372441fe399336607544ab4ce272489e5897
cc @dougalsutherland

**Comment by ocefpaf** [comment] 2017-10-03 15:06
@isuruf what if we do a build `lzo 2.06` and run `lzo >=2.06,<2.11`?

https://abi-laboratory.pro/tracker/timeline/lzo/

**Comment by isuruf** [comment] 2017-10-03 15:10
I don't think that matters. Earlier `lzo 2.06` is coming from defaults and that may be compiled differently to the `conda-forge` package.

**Comment by ocefpaf** [comment] 2017-10-03 15:13
> I don't think that matters. Earlier `lzo 2.06` was coming from defaults and that may be compiled differently to the `conda-forge` package.

What do you suggest?  `>=2.09` ?

**Comment by isuruf** [comment] 2017-10-03 15:15
Figure out what the difference between defaults and conda-forge is, or why 2.06 was needed in the first place.

**Comment by ocefpaf** [comment] 2017-10-03 15:24
> Figure out what the difference between defaults and conda-forge is, or why 2.06 was needed in the first place.

Hard to know. It is one of the old style packages without a recipe or useful metadata.

**Comment by dougalsutherland** [comment] 2017-10-03 19:29
Sorry about this. I don't see any useful debug info in [the Travis log](https://travis-ci.org/pandas-dev/pandas/jobs/282616908), though (just `Slave crashed`) – am I missing something?

Installing the build from the `broken` label I'm able to `import tables`, and can do `DataFrame.to_hdf(..., compression='lzo')` and then `pd.read_hdf` it back in successfully (on Linux). Without any further error messages it's pretty hard to debug any further....

**Comment by dougalsutherland** [comment] 2017-10-03 19:30
Also `lzo` is supposed to be [100% ABI backwards-compatible](https://abi-laboratory.pro/tracker/timeline/lzo/) from 2.01 on, so I don't see how #20 would have changed anything.

**Comment by ocefpaf** [comment] 2017-10-03 19:33
@dougalsutherland it is really hard to debug things like this. The package is functional and some bad interactions with the pandas dependencies are probably the issue here. So no need to be sorry, the changes you submitted were 100% valid!

With that said, the "broken" label is temporary until @jreback gives us feedback on the pining in my test PR. If that reveals the same issue then we need to figure something out, maybe even reverting to `2.06` :unamused:

**Comment by ocefpaf** [comment] 2017-10-03 21:16
Pinning to `lzo 2.06` did not work :confused: 

https://travis-ci.org/ocefpaf/pandas/jobs/282908001

I'll make more experiments to see if we can isolate this. If the `numpy` builds are really the culprit I believe we may have found a bug in `numpy` somewhere... Not sure.

**Comment by isuruf** [comment] 2017-10-03 22:56
Another issue might be https://github.com/conda-forge/pytables-feedstock/pull/18/commits/a594aaa6a152f148d13d508dbbaa69728f179caf

**Comment by ocefpaf** [comment] 2017-10-03 22:59
Ah yes! The `zlib` may be the culprit here.  Let https://travis-ci.org/ocefpaf/pandas/jobs/282908001 finishes and I'll try that.

**Comment by jreback** [comment] 2017-10-04 10:34
confirm pinning lzo=2.06 doesn't change things: https://travis-ci.org/pandas-dev/pandas/jobs/283125250

**Comment by ocefpaf** [comment] 2017-10-04 10:51
I've been doing some testing and nothing so far. I haven't test `zlib` yet, getting there...

**Comment by isuruf** [comment] 2017-10-04 16:07
This is probably fixed by https://github.com/conda-forge/pytables-feedstock/pull/24

**Comment by ocefpaf** [comment] 2017-10-04 16:33
> This is probably fixed by #24

I really hope so, I tested everything and not worked :unamused:

**Comment by ocefpaf** [comment] 2017-10-05 16:48
@jreback I just reinstated @dougalsutherland changes and together with #24 everything seems to work just fine in my pandas test branch. I am closing this, but let me know if you find any issue with build number 5.

**Closed by ocefpaf** 2017-10-05 16:48 UTC

**Comment by jreback** [comment] 2017-10-05 16:58
cool, trying now. will report back.

**Comment by jreback** [comment] 2017-10-05 16:59
https://travis-ci.org/pandas-dev/pandas/jobs/283793714 (building)

**Comment by jreback** [comment] 2017-10-05 18:43
all fixed. thanks @ocefpaf

**Comment by ocefpaf** [comment] 2017-10-05 18:44
Awesome! Thanks!!
